version: "3.9"
name: default
services:
  nginx_default:
    container_name: nginx_default
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../:/var/www
      - ../logs/nginx:/var/log/nginx
    links:
      - php_default
  php_default:
    container_name: php_default
    build: ./php
    working_dir: /var/www
    volumes:
      - ../:/var/www
      - ../logs/php:/var/log
