version: "3.9"
name: default
services:
  nginx_default:
    container_name: nginx_default
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../:/var/www
      - ../logs/nginx:/var/log/nginx
    links:
      - php_default

  db_default:
    container_name: "symfony-assessment-mariadb"
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_USER=${ROOT_USER}
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
    volumes:
      - db_default:/var/lib/mysql:rw
    ports:
      - 3306:3306

  php_default:
    container_name: php_default
    build: ./php
    working_dir: /var/www
    volumes:
      - ../:/var/www
      - ../logs/php:/var/log

volumes:
  db_default:
